In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [5]:
x = torch.FloatTensor(3,4,5)
x

tensor([[[0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22, 2.1715e-18],
         [1.3603e-05, 6.4464e-10, 1.6613e-07, 2.0773e+20, 3.1951e+21],
         [1.0187e-11, 2.6078e+20, 1.3680e+22, 6.8001e+22, 2.1707e-18],
         [4.5447e+30, 7.0062e+22, 2.1715e-18, 4.5447e+30, 7.0062e+22]],

        [[2.1707e-18, 1.9284e+31, 3.2314e-18, 1.8692e+20, 1.3148e+22],
         [1.0072e-11, 2.0429e+20, 1.0622e-05, 3.2767e-09, 6.3011e-10],
         [5.4070e+22, 5.4406e-05, 3.0521e-18, 3.1360e+27, 7.0800e+31],
         [3.1095e-18, 2.9907e+21, 1.1626e+27, 1.6534e+19, 3.0601e+32]],

        [[3.3129e-18, 8.2207e+32, 1.8394e+25, 6.1963e-04, 4.1185e-11],
         [1.4580e-19, 7.1429e+31, 1.5766e-19, 1.0256e-08, 4.1019e-08],
         [3.0441e+12, 4.3350e-08, 6.5930e-10, 2.7002e-06, 1.2751e+16],
         [4.4889e-41, 3.8115e-43, 0.0000e+00, 3.6013e-43, 0.0000e+00]]])

In [6]:
# Выведите его форму (shape)

In [7]:
x.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6 X 10

In [15]:
x = x.view(6,10)
x.shape

torch.Size([6, 10])

In [16]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [18]:
#Нельзя умножить разные размерности.

In [17]:
y = torch.tensor([1, 4, 2, 2, 1])
y * y

tensor([ 1, 16,  4,  4,  1])

In [19]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [20]:
x = x @ x.T
x.shape

torch.Size([6, 6])

In [21]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [22]:
x = torch.tensor([1.], requires_grad = True)
z = torch.tensor([0.5], requires_grad = True)
t = torch.tensor([2.], requires_grad = True)
y = x**3 + z - 75 * t

In [23]:
y.backward()

In [24]:
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [25]:
# Создайте единичный тензор размера 5x6

In [26]:
x = torch.ones(5,6)

In [27]:
# Переведите его в формат numpy

In [28]:
x = x.numpy()